#include "gateway_config.h"
#include "app_config.h"
#include "nvs.h"
#include "string.h"
#include "esp_log.h"
static const char *TAG="config";
static void read_text(nvs_handle_t h,const char *key,char *out,size_t n,const char *fallback){size_t len=n;if(nvs_get_str(h,key,out,&len)!=ESP_OK)strlcpy(out,fallback,n);}
bool gateway_config_valid(const gateway_config_t *c){if(!c||!c->mqtt_topic_uplink[0]||!c->gateway_id[0])return false;if(c->mode==GATEWAY_MODE_AP_ESPNOW)return true;return c->wifi_ssid[0]&&c->mqtt_broker[0];}
esp_err_t gateway_config_save(const gateway_config_t *c){if(!gateway_config_valid(c))return ESP_ERR_INVALID_ARG;nvs_handle_t h;esp_err_t e=nvs_open("gateway",NVS_READWRITE,&h);if(e!=ESP_OK)return e;e=nvs_set_u8(h,"mode",(uint8_t)c->mode);if(e==ESP_OK)e=nvs_set_str(h,"wifi_ssid",c->wifi_ssid);if(e==ESP_OK)e=nvs_set_str(h,"wifi_password",c->wifi_password);if(e==ESP_OK)e=nvs_set_str(h,"mqtt_broker",c->mqtt_broker);if(e==ESP_OK)e=nvs_set_str(h,"mqtt_topic_uplink",c->mqtt_topic_uplink);if(e==ESP_OK)e=nvs_set_str(h,"gateway_id",c->gateway_id);if(e==ESP_OK)e=nvs_commit(h);nvs_close(h);return e;}
esp_err_t gateway_config_factory_reset(void){nvs_handle_t h;esp_err_t e=nvs_open("gateway",NVS_READWRITE,&h);if(e==ESP_ERR_NVS_NOT_FOUND)return ESP_OK;if(e!=ESP_OK)return e;e=nvs_erase_all(h);if(e==ESP_OK)e=nvs_commit(h);nvs_close(h);return e;}
esp_err_t gateway_config_load(gateway_config_t *c){if(!c)return ESP_ERR_INVALID_ARG;memset(c,0,sizeof(*c));c->mode=GATEWAY_MODE_AP_ESPNOW;strlcpy(c->mqtt_topic_uplink,APP_MQTT_TOPIC,sizeof(c->mqtt_topic_uplink));strlcpy(c->gateway_id,APP_GATEWAY_ID,sizeof(c->gateway_id));nvs_handle_t h;esp_err_t e=nvs_open("gateway",NVS_READONLY,&h);if(e==ESP_OK){uint8_t mode=0;if(nvs_get_u8(h,"mode",&mode)==ESP_OK&&mode<=GATEWAY_MODE_WIFI_MQTT)c->mode=(gateway_mode_t)mode;read_text(h,"wifi_ssid",c->wifi_ssid,sizeof(c->wifi_ssid),"");read_text(h,"wifi_password",c->wifi_password,sizeof(c->wifi_password),"");read_text(h,"mqtt_broker",c->mqtt_broker,sizeof(c->mqtt_broker),"");read_text(h,"mqtt_topic_uplink",c->mqtt_topic_uplink,sizeof(c->mqtt_topic_uplink),APP_MQTT_TOPIC);read_text(h,"gateway_id",c->gateway_id,sizeof(c->gateway_id),APP_GATEWAY_ID);nvs_close(h);}ESP_LOGI(TAG,"configuration loaded mode=%s wifi/broker configured=%s/%s",c->mode==GATEWAY_MODE_AP_ESPNOW?"ap-esnow":"wifi-mqtt",c->wifi_ssid[0]?"yes":"no",c->mqtt_broker[0]?"yes":"no");return ESP_OK;}
