#include "provisioning_web.h"
#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_system.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "string.h"
#include "stdio.h"
#include "stdlib.h"
#include "worker_status.h"
#include "alert_history.h"
#include "led_status.h"

static httpd_handle_t server;
static bool server_started;
static const char *TAG = "provisioning";

static const char PAGE[] = "<!doctype html><html><head><meta name='viewport' content='width=device-width'><title>MineMesh Gateway</title><style>body{font-family:system-ui;background:#101827;color:#eef;padding:20px;max-width:900px;margin:auto}.card{background:#1d2a40;border-radius:14px;padding:18px;margin:12px 0;box-shadow:0 5px 20px #0005}h1{color:#55d6be}button{background:#55d6be;border:0;padding:12px 18px;border-radius:8px;font-weight:bold}input,select{padding:9px;margin:5px;border-radius:6px;border:1px solid #557;background:#0e1625;color:#fff}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-bottom:1px solid #456}.critical{color:#ff5263;font-size:1.4em}</style></head><body><h1>MineMesh Gateway</h1><div class='card'><h2>Operating mode</h2><form method='post' action='/api/config'><select name='mode' id='mode' onchange='toggle()'><option value='0'>AP + ESP-NOW receive only</option><option value='1'>Wi-Fi + MQTT bridge</option></select><div id='net'><input name='wifi_ssid' placeholder='Wi-Fi SSID'><input name='wifi_password' type='password' placeholder='Wi-Fi password'><input name='mqtt_broker' placeholder='mqtt://192.168.1.20:1883'></div><input name='mqtt_topic_uplink' value='minemesh/v1/uplink'><input name='gateway_id' value='gateway'><br><button>Save and reboot</button></form></div><div class='card'><h2>Live workers</h2><div id='summary'>Loading...</div><div id='alert' class='critical'></div><button onclick='ack()'>Acknowledge alert</button><h2>Critical alerts</h2><div id='alerts'></div><table><thead><tr><th>Worker</th><th>Status</th><th>Age</th><th>Type</th><th>Priority</th><th>RSSI</th></tr></thead><tbody id='workers'></tbody></table></div><script>function toggle(){net.style.display=mode.value==='1'?'block':'none'}async function ack(){await fetch('/api/alerts/ack',{method:'POST'});refresh()}async function refresh(){try{let d=await(await fetch('/api/workers')).json();summary.textContent='Online '+d.online+' / Known '+d.known;workers.textContent='';d.workers.forEach(w=>{let tr=document.createElement('tr');[w.source_id,w.online?'ONLINE':'OFFLINE',w.last_seen_ms+' ms',w.message_type,w.priority,w.rssi].forEach(x=>{let td=document.createElement('td');td.textContent=x;tr.appendChild(td)});workers.appendChild(tr)});let a=await(await fetch('/api/alerts')).json();document.getElementById('alert').textContent=a.active?'CRITICAL ALERT ACTIVE':'No active critical alert';let alertList=document.getElementById('alerts');alertList.textContent='';a.alerts.forEach(x=>{let p=document.createElement('p');p.textContent=x.type+' '+x.reason+' | '+x.source_id+' | RSSI '+x.rssi+(x.active?' | ACTIVE':'');alertList.appendChild(p)})}catch(e){summary.textContent='Gateway unavailable'}}toggle();setInterval(refresh,3000);refresh();</script></body></html>";

static bool field(const char *body,const char *key,char *out,size_t cap){char needle[48];snprintf(needle,sizeof(needle),"%s=",key);const char *p=strstr(body,needle);if(!p)return false;p+=strlen(needle);size_t n=0;while(p[n]&&p[n]!='&'&&n+1<cap)n++;for(size_t i=0;i<n;i++)out[i]=p[i]=='+'?' ':p[i];out[n]='\0';return n>0;}
static esp_err_t page(httpd_req_t *r){httpd_resp_set_type(r,"text/html");return httpd_resp_send(r,PAGE,HTTPD_RESP_USE_STRLEN);}
static esp_err_t workers(httpd_req_t *r){char body[2048];size_t n=worker_status_json(body,sizeof(body));httpd_resp_set_type(r,"application/json");return httpd_resp_send(r,body,n);}
static esp_err_t alerts(httpd_req_t *r){char body[3072];size_t n=alert_history_json(body,sizeof(body));httpd_resp_set_type(r,"application/json");return httpd_resp_send(r,body,n);}
static esp_err_t acknowledge(httpd_req_t *r){alert_history_acknowledge();led_status_acknowledge();return httpd_resp_sendstr(r,"Alert acknowledged");}
static esp_err_t save(httpd_req_t *r){char body[512];if(r->content_len<=0||r->content_len>=sizeof(body)){httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"Form too large");return ESP_OK;}int got=httpd_req_recv(r,body,r->content_len);if(got<=0){httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"No form");return ESP_OK;}body[got]='\0';gateway_config_t c={0};char mode[4];if(!field(body,"mode",mode,sizeof(mode))||!field(body,"mqtt_topic_uplink",c.mqtt_topic_uplink,sizeof(c.mqtt_topic_uplink))||!field(body,"gateway_id",c.gateway_id,sizeof(c.gateway_id))){httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"Required fields missing");return ESP_OK;}c.mode=(gateway_mode_t)atoi(mode);field(body,"wifi_ssid",c.wifi_ssid,sizeof(c.wifi_ssid));field(body,"wifi_password",c.wifi_password,sizeof(c.wifi_password));field(body,"mqtt_broker",c.mqtt_broker,sizeof(c.mqtt_broker));if(!gateway_config_save(&c)){httpd_resp_sendstr(r,"Saved; rebooting");vTaskDelay(pdMS_TO_TICKS(400));esp_restart();}else httpd_resp_send_err(r,HTTPD_400_BAD_REQUEST,"Invalid configuration");return ESP_OK;}
esp_err_t provisioning_web_start(void){if(server_started)return ESP_OK;httpd_config_t cfg=HTTPD_DEFAULT_CONFIG();cfg.stack_size=8192;if(httpd_start(&server,&cfg)!=ESP_OK)return ESP_FAIL;httpd_uri_t a={.uri="/",.method=HTTP_GET,.handler=page};httpd_uri_t b={.uri="/api/workers",.method=HTTP_GET,.handler=workers};httpd_uri_t c={.uri="/api/alerts",.method=HTTP_GET,.handler=alerts};httpd_uri_t d={.uri="/api/alerts/ack",.method=HTTP_POST,.handler=acknowledge};httpd_uri_t e={.uri="/api/config",.method=HTTP_POST,.handler=save};httpd_register_uri_handler(server,&a);httpd_register_uri_handler(server,&b);httpd_register_uri_handler(server,&c);httpd_register_uri_handler(server,&d);httpd_register_uri_handler(server,&e);server_started=true;ESP_LOGI(TAG,"dashboard available at http://192.168.4.1");return ESP_OK;}
