#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#define APP_DEVICE_ID "worker-001"
#define APP_FIRMWARE_VERSION "1.0.0"
#define APP_DESTINATION_ID "gateway"
#define APP_HEARTBEAT_INTERVAL_SEC 10
#define APP_TELEMETRY_INTERVAL_SEC 15
#define APP_SOS_LONG_PRESS_MS 2000
#define APP_FALL_CONFIRM_SEC 10
#define APP_FALL_ALERT_ON_SUSPECT 1
#define APP_INACTIVITY_TIMEOUT_SEC 60
#define APP_IMU_SAMPLE_HZ 50
#define APP_TTL_DEFAULT 8
#define APP_I2C_SDA_GPIO 4
#define APP_I2C_SCL_GPIO 5
#define APP_MPU6050_ADDR 0x68
#define APP_SOS_BUTTON_GPIO 9
#define APP_BUZZER_GPIO 6
#define APP_BATTERY_ADC_GPIO 0
#define APP_LED_GPIO 8
#define APP_GATEWAY_CHANNEL 1
#define APP_GATEWAY_MAC "A0:F2:62:01:17:31"
#define APP_MOTION_DELTA_G 0.12f
#define APP_FALL_SPIKE_G 2.5f
#define APP_FALL_ORIENTATION_G 0.45f
#define APP_FREE_FALL_G 0.35f
#define APP_JSON_MAX 240

#endif
