# Auto-generated by Firmgen — DO NOT EDIT.
# Explicit list of firmware sources + include dirs, refreshed before every
# build. Replaces the old file(GLOB ...) (which cached stale results and could
# escape the project). FW_ROOT is set by the including main/CMakeLists.txt.

set(APP_SOURCES
    "${FW_ROOT}/app/app.c"
    "${FW_ROOT}/app/gateway.c"
    "${FW_ROOT}/services/alert_history.c"
    "${FW_ROOT}/services/boot_button.c"
    "${FW_ROOT}/services/cli.c"
    "${FW_ROOT}/services/dedup.c"
    "${FW_ROOT}/services/espnow_rx.c"
    "${FW_ROOT}/services/gateway_config.c"
    "${FW_ROOT}/services/led_status.c"
    "${FW_ROOT}/services/mqtt_bridge.c"
    "${FW_ROOT}/services/protocol_v1.c"
    "${FW_ROOT}/services/provisioning_web.c"
    "${FW_ROOT}/services/wifi_service.c"
    "${FW_ROOT}/services/worker_status.c"
    "${FW_ROOT}/utils/helpers/helpers.c"
    "${FW_ROOT}/utils/logger/logger.c"
)

set(FW_INCLUDE_DIRS
    "${FW_ROOT}"
    "${FW_ROOT}/app"
    "${FW_ROOT}/configs"
    "${FW_ROOT}/interfaces"
    "${FW_ROOT}/services"
    "${FW_ROOT}/utils/helpers"
    "${FW_ROOT}/utils/logger"
)
